name = "auditor-edge"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# R2 bucket for PDFs/CSVs and evidence files
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "auditor"

# D1 database for runs, findings, events
[[d1_databases]]
binding = "DB"
database_name = "auditor"
database_id = "deb22e02-1ce1-448f-b88f-6bea53de193f"

# Vectorize index for embeddings
[[vectorize]]
binding = "VEC"
index_name = "auditor-index"

# Durable Objects for WebSocket state
[[durable_objects.bindings]]
name = "RUNROOM"
class_name = "RunRoom"
script_name = "auditor-edge"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RunRoom"]

# AI Gateway configuration
[vars]
AI_GATEWAY_URL = "https://gateway.ai.cloudflare.com/v1/99b429887ccf20faca6cd78dbeb0a207/auditor-gateway/google-ai-studio"

# Placeholder for Workers AI (if needed later)
[ai]
binding = "AI"

# Secrets (set via: wrangler secret put <NAME>)
# TURNSTILE_SECRET
# JWT_SECRET

# Optional: Cron trigger to unlock stuck jobs every 10 minutes
# Uncomment to enable:
# [triggers]
# crons = ["*/10 * * * *"]

